name: CI  

on:
  pull_request:
    branches: ["main"]

jobs:
  tests:
    name: Docker/Go Tests
    runs-on: ubuntu-latest

    services:
      dind:
        image: docker:23.0-rc-dind-rootless
        ports:
          - 2375:2375

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4.0.0
        with:
          go-version-file: go.mod

      - name: Fetch required Go modules
        run: go mod download && go mod verify
  
      - name: Run Go tests
        run: go test -v ./app/...

      - name: Build and spin-up the Docker container
        uses: isbang/compose-action@v1.4.1
        with:
          up-flags: "--build"
   
      - name: Test the Go server endpoints
        run: |
          curl http://localhost:8080/
          curl http://localhost:8080/health
