name: Formatting

on:
  pull_request:
    branches: ["main"]


jobs:
  lint:
    name: Lint Changed Files
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:  
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_EXCLUDE: /.*_test\.go
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          DOCKERFILE_HADOLINT_FILE_NAME: .hadolint.yaml
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_GO: true
          VALIDATE_YAML: true
